version: "3.9"

services:
  web:
    build: .
    command: python ./manage.py runserver 0.0.0.0:8000
    # command: python ./manage.py runserver 0.0.0.0:$PORT
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      # - $PORT
    depends_on:
      - db
      # - django

  # django:
  #   image: django-docker:0.0.1
  #   build: .
  #   ports:
  #     - "9000:9000"

  db:
    image: postgres
    environment:
      POSTGRES_DB: fairsharetracker
      POSTGRES_USER: fairsharetracker
      POSTGRES_PASSWORD: 1995
