# Generated by Django 5.0 on 2023-12-30 12:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('split_type', models.CharField(choices=[('equal', 'Equal Split')], max_length=50)),
                ('include_payer', models.BooleanField(default=False)),
                ('user_included', models.BooleanField(default=True)),
                ('payer_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses_paid', to=settings.AUTH_USER_MODEL)),
                ('shared_users', models.ManyToManyField(blank=True, related_name='shared_expenses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
